In [ ]:
import numpy as np

# arr = np.array([1, 2, 3, 4])
# print(type(arr))
# print(arr[0])

list_1 = [1,3,5]
print(type(list_1))
x  = np.array(list_1)
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[-1])


1
5


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# print(arr.shape)
print(arr[2:9])

[3 4 5 6 7 8 9]


In [ ]:
# Slice elements from index 1 to index 5 from the following array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
# Return every other element from index 1 to index 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[1:2 , 1:4])

[[7 8 9]]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr.shape)

(2, 5)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
np.arange()

### Exercises:

1. Create a 4X2 integer array and Prints its attributes

The shape of an array.

Array dimensions.

The Length of each element of the array in bytes.

2. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
\

Creating 5X2 array using numpy.arange

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]

3. Following is the provided numPy array. Return array of items by taking the third value from all rows

sampleArray = numpy.array([[11 ,22, 33],
                           [44, 55, 66],
                          [77, 88, 99]])



In [ ]:
firstArray = np.empty([4,2], dtype = np.uint16)
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[    0     0]
 [    0 49152]
 [32767  3756]
 [32764     0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


In [ ]:
import numpy as np
print("Creating 5X2 array using numpy.arange")
sampleArray = np.arange(100, 200, 10).reshape(5,2)
print(sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)