In [3]:
import numpy as np

1. Create a 4X2 integer array and Prints its attributes

The shape of an array.

Array dimensions.

The Length of each element of the array in bytes.

In [4]:
array_1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])
print("Shape of the array:", array_1.shape)
print("Data type of the array:", array_1.dtype)
print("Number of dimensions of the array:", array_1.ndim)
print("Total number of elements in the array:", array_1.size)
print("Size of each element in bytes:", array_1.itemsize)
print("Total number of bytes consumed by the elements of the array:", array_1.nbytes)

Shape of the array: (4, 2)
Data type of the array: int64
Number of dimensions of the array: 2
Total number of elements in the array: 8
Size of each element in bytes: 8
Total number of bytes consumed by the elements of the array: 64




2. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10




In [5]:
array_2 =  np.arange(100, 200, 10).reshape(5, 2)


3. Following is the provided numPy array. Return array of items by taking the third value from all rows

sampleArray = numpy.array([[11 ,22, 33],
                           [44, 55, 66],
                          [77, 88, 99]])

In [6]:
sampleArray = np.array([[11 ,22, 33],
                           [44, 55, 66],
                          [77, 88, 99]])
print("Printing Sample Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing Sample Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]
