# Getting Started work with Numpy

In [ ]:
# As you know that Numpy is the Library of python so before work with Numpy we have to import Numpy

import numpy as np

# np is just like a variable or handle we used np to call numpy functions

In [ ]:
# For define an array in Numpy

In [ ]:
x = np.array([1,3,5,7])

In [ ]:
x

array([1, 3, 5, 7])

In [ ]:
# Numpy give us some functions of generating arrays
# zeros(row , column): It generates the array wiith all elements 0
# ones(rows, columns): It generates the array with all elements 1
# empty(): It generates the array with random numbers

In [ ]:
np.zeros((4,2)) #an Array of zeros with 4 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.empty((4,6))

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
# we can also generate the array of the even numbers an odd numbers for this we use arange()

np.arange(0,20,2) #(starting value , ending value-1,diffrence)

# You know that the ending value is not included in array thats why I write value-1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])